name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"  # ✅ Use a stable version

      - name: Install Dependencies
        run: |
          python -m venv .venv  # ✅ Create virtual environment
          source .venv/bin/activate  # ✅ Activate venv
          pip install --upgrade pip
          pip install -r requirements.txt  # ✅ Install dependencies

      - name: Verify Installation
        run: |
          source .venv/bin/activate
          python -m pip list  # ✅ Check installed packages

      - name: Run Tests
        run: |
          source .venv/bin/activate  # ✅ Ensure venv is activated
          pytest --maxfail=1 --disable-warnings  # ✅ Run tests
